set = set()
n = input("Enter the number : ")
set.add(int(n))
n = input("Enter the number : ")
set.add(int(n))
n = input("Enter the number : ")
set.add(int(n))
n = input("Enter the number : ")
set.add(int(n))
n = input("Enter the number : ")
set.add(int(n))
n = input("Enter the number : ")
set.add(int(n))
n = input("Enter the number : ")
set.add(int(n))
n = input("Enter the number : ")
set.add(int(n))

print(set)